site_name: 文档
docs_dir: "mkdocs"
repo_url: https://github.com/idcos/cloudiac-docs
repo_name: cloudiac-docs
edit_uri: edit/master/docs/mkdocs/
theme:
  language: zh
  name: material
  logo: assets/svg/icon.svg
  favicon: assets/svg/icon.svg
  palette:
    primary: deep purple
  icon:
    repo: fontawesome/brands/github
plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\.]+' # 分词分隔符
extra:
  version:
    provider: mike
    default: latest
extra_css:
  - "assets/css/custom.css"
  - "assets/css/simpleLightbox.min.css"
extra_javascript:
  - 'assets/js/jquery.min.js'
  - 'assets/js/simpleLightbox.min.js'
  - 'assets/js/custom.js'
  - "assets/js/jquery.min.js"
  - "assets/js/simpleLightbox.min.js"
  - "assets/js/custom.js"
markdown_extensions:
  - markdown.extensions.attr_list
  - meta
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "_"
  - footnotes
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:mermaid2.fence_mermaid"

nav:
  - "快速入门":
    - "创建组织和项目": quick-start/create-org-project.md
    - "创建Stack": quick-start/create-template.md
    - "部署环境": quick-start/deploy-env.md
    - "导入Stack": quick-start/stack-use.md

  - "产品介绍":
    - "产品概述": index.md
    - "术语解释": intro/product-glossary.md
    - "产品优势": intro/product-advantage.md
    - "产品构架": intro/product-architecture.md

  - "产品手册":
    - "组织/项目/角色": manual/org-project-role.md
    - "组织/项目概览": manual/org-project-overview.md
    - "VCS 管理": manual/vcs.md
    - "Stack管理": manual/templates.md
    - "变量与资源账号": manual/res-account-variable.md
    - "环境管理": manual/env.md
    - "环境高级功能": manual/env-advanced.md
    - "安全合规": manual/compliance.md
    - "Stack Pipeline": manual/pipeline.md
    - "费用预估和统计": manual/env-cost.md
    - "通用功能": manual/others.md
    - "Token 获取": manual/vcs-token.md

  - "IaC Exchange 手册":
    - "IaC Exchange简介": manual/registry.md
    - "Providers": manual/registry-providers.md
    - "Modules": manual/registry-modules.md
    - "策略组": manual/registry-polices.md
    - "Provider 发布": "cases/provider-publish.md"
    - "Module 发布": "cases/module-publish.md"
    - "策略组发布": "cases/policy-group-publish.md"
    - "获取签名密钥": cases/create-gpg-key.md
    - "添加签名密钥": cases/add-gpg-key.md
    - "vcs集成": cases/create-vcs.md

  - "用户场景":
    - "环境即服务": "cases/env-as-service.md"
    - "合规检查": "cases/check-policy.md"
    - "使用合规策略限制测试环境的机器规格": "cases/opa-instance-type.md"
    - "自定义合规策略": "cases/git-create-policy-group.md"
    - "使用IaC Exchange中的策略组": "cases/registry-policygroup.md"
    - "变更漂移检测": "cases/drift_detection.md"
    - "在环境资源中部署应用": "cases/ssh_key.md"
    - "自定义terraform版本": "cases/cloud_template.md"
    - "定时销毁环境": "cases/env-auto-destroy.md"
    - "添加部署失败通知": "cases/deploy-failed-notification.md"
    - "通过 tfvars 文件预定义变量": "cases/tfvars.md"

  - "部署安装":
    - "容器部署": installation/container.md
    - "二进制部署": installation/linux.md
    - "一键部署": installation/shell-deployment.md
    - "Consul开启acl和tls": installation/consul.md
    - "Consul高可用部署": installation/consul-cluster.md

#  - "Releases": releases.md
  - "视频介绍": https://space.bilibili.com/2138433328/channel/seriesdetail?sid=1908688

#  - "API文档":
#    - "API简介": api-docs/index.md
#  - "常见问题":
#    - "常见问题": answer-questions/index.md
